name: Release

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: macos-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'preview'
          
      - name: Install maui
        run: dotnet workload install maui

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Publish
          cake-version: 1.3.0
        env:
          NUGETKEY: ${{ secrets.NUGETKEY }}
